### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1

### ISSUE THREAD

**Issue by Mavelous** [git-big-picture/git-big-picture#34]
I'm trying to run git-big-picture on a very large Git repo at work.  For obvious reasons, I can't provide a link to the repository.  But the error/output is:

```
$ git big-picture -o my_project.png
Traceback (most recent call last):
  File "/cygdrive/c/Program Files/cygwin64/home/mavelous/bin/git-big-picture", line 1000, in <module>
    main(opts, args)
  File "/cygdrive/c/Program Files/cygwin64/home/mavelous/bin/git-big-picture", line 960, in main
    dot_output = run_dot(output_settings[FORMAT], dot_file_lines)
  File "/cygdrive/c/Program Files/cygwin64/home/mavelous/bin/git-big-picture", line 307, in run_dot
    out, err = p.communicate(input='\n'.join(dot_file_lines).encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 73: ordinal not in range(128)
```

**Comment by julescopeland** [comment]
I get this as well, running on OSX.

For reference (if it helps):
```
> echo $LC_CTYPE
en_GB.UTF-8
> locale charmap
UTF-8
> python -c "import sys; print(sys.stdout.encoding)"
UTF-8
```

**Comment by hartwork** [comment]
The interesting part is that line `out, err = p.communicate(input='\n'.join(dot_file_lines).encode('utf-8'))` should not have anything to *de*code in Python 3: `.communicate` wants bytes and we do give raw bytes to it.

If I cut the related code down to its essence I get to this:

```python
from __future__ import print_function
import subprocess
import sys

p = subprocess.Popen(['cat'],
                     stdin=subprocess.PIPE,
                     stdout=subprocess.PIPE,
                     stderr=subprocess.PIPE)

out, err = p.communicate(input='\n'.join(['one', 'two', chr(0xd1)]).encode('utf-8'))
```

Running that with Python 3.8 works well, running it with Python 2.7 will crash with the exact error that @Mavelous has shared on top:

```console
# python2 foo.py 
Traceback (most recent call last):
  File "foo.py", line 10, in <module>
    out, err = p.communicate(input='\n'.join(['one', 'two', chr(0xd1)]).encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 8: ordinal not in range(128)
```

As result, I am concluding that git-big-picture has been run with Python 2 rather than 3 here and that latest `master` (and the latest release) are not affected. So I'll close the ticket as obsolete (or not a bug). If that turns out too eager, I'm happy to re-open.
